### PR TITLE
edit README to add snippet about cache:clean via command line

### PR DESCRIPTION
**Pull request by giuseppemorelli**
Refer to #5 

Just a reminder about clear cache via command line
It's quite simple to remember for "non-expert terminal" people.

### CODE REVIEW

**Comment by mmenozzi** [comment]
Hi @giuseppemorelli,
what you say in the README is correct but I'd put more emphasis on the fact that the environment variable must be **always** set. Not only for the `cache:clean` command.

For example if someone works with the config cache disabled and runs `export MAGE_ENVIRONMENT=dev && bin/magento cache:clean` and then some other CLI command which requires config overridden with `dev` values it will not work.

What do you think?

**Comment by giuseppemorelli** [comment]
Hi @mmenozzi ,
you're right. I forgot the part of: you need to have **always** MAGE_ENVIRONMENT with a value.
I've changed my pull request.

**Comment by mmenozzi** [comment]
Perfect! Thank you @giuseppemorelli !

**Comment by mmenozzi** [comment]
I'm going to merge this PR even if the CI build is broken because, obviously,  the README change is not the reason why it's broken (I think is related to something changed with a recent version of Composer).

**Pull request merged**
